<a href="https://colab.research.google.com/github/petko5/AIND-Isolation-master/blob/master/Copy_of_DenseDepth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#clone DenseDepth
!git clone https://github.com/ialhashim/DenseDepth.git

Cloning into 'DenseDepth'...
remote: Enumerating objects: 263, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 263 (delta 8), reused 15 (delta 4), pack-reused 242
Receiving objects: 100% (263/263), 12.13 MiB | 32.00 MiB/s, done.
Resolving deltas: 100% (127/127), done.


In [2]:
#get weights
!wget https://s3-eu-west-1.amazonaws.com/densedepth/nyu.h5 -O ./DenseDepth/nyu.h5

--2021-06-26 17:03:39--  https://s3-eu-west-1.amazonaws.com/densedepth/nyu.h5
Resolving s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)... 52.218.28.107
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|52.218.28.107|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 172897376 (165M) [application/h5]
Saving to: ‘./DenseDepth/nyu.h5’

./DenseDepth/nyu.h5 100%[===================>] 164.89M  20.6MB/s    in 9.2s    

2021-06-26 17:03:49 (17.9 MB/s) - ‘./DenseDepth/nyu.h5’ saved [172897376/172897376]



In [4]:
#!wget  https://github.com/tensorflow/tensorflow/archive/v1.15.3.tar.gz

#get correct TF version installed to match DenseDepth (not TF 2.0+)
!pip install tensorflow-gpu==1.15.3


     |████████████████████████████████| 110.5MB 65kB/s 
     |████████████████████████████████| 3.8MB 48.7MB/s 
     |████████████████████████████████| 512kB 42.1MB/s 
     |████████████████████████████████| 51kB 9.9MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp37-none-any.whl size=7557 sha256=c5308247da71a2bb86b971aad56087fdde5689014d05eb1862405bfed4ce8b7e
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.12.1 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
ERROR: kapre 0.3.5 has requirement tensorflow>=2.0.0, but you'll have tensorflow 1.15.3 which is incompatible.
  Found existing installation: tensorboard 2.5.0
    Uninstalling tensorboard-2.5.0:
      Successfully uninstalled tensorboard-2.5.0
  Found existing installation: tensorflow-estimator 2.5.0
    Uninstalling tensorflow-estimator-2.5.0:
      Successfully uninstalled tensor

In [6]:
from matplotlib import pyplot as plt
from skimage import io
!cd DenseDepth; python test.py

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    from keras.models import load_model
  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/usr/local/lib/python3.7/dist-packages/keras/models.py", line 19, in <module>
    from keras import backend
  File "/usr/local/lib/python3.7/dist-packages/keras/backend.py", line 37, in <module>
    from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context' (/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/eager/context.py)


In [7]:
#need to change original code to display single image vs array of images
plt.figure(figsize=(20,20))
plt.imshow( io.imread('./DenseDepth/petko_test.png') )

FileNotFoundError: ignored

<Figure size 1440x1440 with 0 Axes>

In [ ]:
import os
os.listdir()


from pathlib import Path
data_folder = Path("DenseDepth/")
file_to_open = data_folder / "petko_test.png"

In [ ]:
import numpy as np
#Kinect settings for NYU v2 depth
fx_rgb = 5.1885790117450188e+02;
fy_rgb = 5.1946961112127485e+02;
cx_rgb = 3.2558244941119034e+02;
cy_rgb = 2.5373616633400465e+02;
K=np.array([[fx_rgb, 0, cx_rgb, 0],[0, fy_rgb, cy_rgb, 0],[0,0, 1, 0]])
print (K.shape)



from PIL import Image
petko_test_image= np.clip(np.asarray(Image.open((open(file_to_open, 'rb')) ), dtype=float) / 255, 0, 1)
print (petko_test_image.shape)
petko_test2=petko_test_image.copy()


'''
print(petko_test_image)

plt.figure(figsize=(1,1))
plt.imshow(petko_test_image)
petko_test_image.shape

np.linalg.inv(K) * np.array([0, 0, 1])

'''


(3, 4)
(240, 320)


'\nprint(petko_test_image)\n\nplt.figure(figsize=(1,1))\nplt.imshow(petko_test_image)\npetko_test_image.shape\n\nnp.linalg.inv(K) * np.array([0, 0, 1])\n\n'

In [ ]:
print (np.min(petko_test_image))
#K_inverse formula for Kinect
K_inv = np.array([[1/fx_rgb, 0, -cx_rgb/fx_rgb], [0,1/fy_rgb,-cy_rgb/fy_rgb], [0, 0, 1]])

#iPhone SE coefficients
coeff=6.3
u0=1.9989257139351400e+03
v0=1.4611872259677407e+03
fx_rgb=3.3180846117248893e+03
fy_rgb=3.3164848380172425e+03

K=np.array([[fx_rgb,0.0000000000000000e+00,u0],
            [0,fy_rgb,v0],
           [0,0,1]])



K_inv=np.linalg.inv(K)
print (K_inv.shape,petko_test_image.shape)


#create 3D matrix
#multi=np.array([petko_test_image,petko_test_image,petko_test_image])
#petko_rgb= (np.stack(multi,axis=-1))

print (petko_test_image.shape)


#from https://stackoverflow.com/questions/23581238/distance-measurement-using-disparity-map
#here x,y image coordinates of the plane are 0,0 in "coord" matrix below

coord=np.array([0, 0, 1])
u= np.matmul(K_inv,coord.transpose())
#print (u.shape)
#dist=petko_test_image[:, :, np.newaxis]*u
#dist=petko_test_image*u
dist2=np.matmul(petko_test2[:, :, np.newaxis],u[np.newaxis,:])
print (dist2)


'''
import numpy as np
fx_rgb = 5.1885790117450188e+02;
fy_rgb = 5.1946961112127485e+02;
cx_rgb = 3.2558244941119034e+02;
cy_rgb = 2.5373616633400465e+02;
K_inv = np.array([[1/fx_rgb, 0, -cx_rgb/fx_rgb], [0,1/fy_rgb,-cy_rgb/fy_rgb], [0, 0, 1]])

K=np.array([[fx_rgb, 0, cx_rgb, 0],[0, fy_rgb, cy_rgb, 0],[0,0, 1, 0]])
print (K.shape)
K_inv * np.array([0, 0, 1])
'''

0.18823529411764706
(3, 3) (240, 320)
(240, 320)
(3,)
[[[-0.21900921 -0.17047946  0.34901961]
  [-0.2091661  -0.16281746  0.33333333]
  [-0.20670532 -0.16090196  0.32941176]
  ...
  [-0.19686221 -0.15323996  0.31372549]
  [-0.19686221 -0.15323996  0.31372549]
  [-0.20424454 -0.15898646  0.3254902 ]]

 [[-0.21654843 -0.16856396  0.34509804]
  [-0.21900921 -0.17047946  0.34901961]
  [-0.2091661  -0.16281746  0.33333333]
  ...
  [-0.19932299 -0.15515546  0.31764706]
  [-0.19932299 -0.15515546  0.31764706]
  [-0.19932299 -0.15515546  0.31764706]]

 [[-0.21654843 -0.16856396  0.34509804]
  [-0.21654843 -0.16856396  0.34509804]
  [-0.21162688 -0.16473296  0.3372549 ]
  ...
  [-0.20424454 -0.15898646  0.3254902 ]
  [-0.20424454 -0.15898646  0.3254902 ]
  [-0.20178377 -0.15707096  0.32156863]]

 ...

 [[-0.1427251  -0.11109897  0.22745098]
  [-0.13780355 -0.10726797  0.21960784]
  [-0.13288199 -0.10343697  0.21176471]
  ...
  [-0.13534277 -0.10535247  0.21568627]
  [-0.14026433 -0.10918347  0.

'\nimport numpy as np\nfx_rgb = 5.1885790117450188e+02;\nfy_rgb = 5.1946961112127485e+02;\ncx_rgb = 3.2558244941119034e+02;\ncy_rgb = 2.5373616633400465e+02;\nK_inv = np.array([[1/fx_rgb, 0, -cx_rgb/fx_rgb], [0,1/fy_rgb,-cy_rgb/fy_rgb], [0, 0, 1]])\n\nK=np.array([[fx_rgb, 0, cx_rgb, 0],[0, fy_rgb, cy_rgb, 0],[0,0, 1, 0]])\nprint (K.shape)\nK_inv * np.array([0, 0, 1])\n'

In [ ]:
img_h=240
img_w=320
maxD=1 #maxD for DenseDepth is 10 
depth=petko_test2

#from https://towardsdatascience.com/inverse-projection-transformation-c866ccedef1c
cam_points = np.zeros((img_h * img_w, 3))
i = 0
# Loop through each pixel in the image
for v in range(height):
    for u in range(width):
        # Apply equation in fig 5
        x = (u - u0) * maxD* depth[v, u] / fx_rgb
        y = (v - v0) * maxD* depth[v, u] / fy_rgb
        z = maxD*depth[v, u]
        cam_points[i] = (x, y, z)
        i += 1

In [ ]:
a=(207*.5,301*.5)
cam_points_xyz=cam_points.reshape(240,320,3)

#Distance Measurement. a and b represent the 2 x,y image points we are interested in measuring the distance between

def distance_meas(matx,a,b):
    deltax=np.square(matx[a][0]-matx[b][0])
    deltay=np.square(matx[a][1]-matx[b][1])
    deltaz=np.square(matx[a][2]-matx[b][2])
    return (np.sqrt((deltax+deltay+deltaz)))

dist=distance_meas(cam_points_xyz,(int(105*.5),int(204*.5)),(int(308*.5),int(206*.5)))

print (b)

(103.5, 150.5)
[-1.54170656 -1.21811783  2.8627451 ]
1.2363097495357511


0.41914173105946545

In [ ]:
import cv2
print (petko_test2,u.shape)


K=np.array([[3.3180846117248893e+03/coeff,0.0000000000000000e+00,1.9989257139351400e+03/coeff,0],[0,3.3164848380172425e+03/coeff,1.4611872259677407e+03/coeff,0],
           [0,0,1,0]])


t=cv2.reprojectImageTo3D(petko_test2[:, :, np.newaxis],K)


#cv2.perspectiveTransform(petko_test2,K_inv.transpose())

[[0.17254902 0.17647059 0.17254902 ... 0.17254902 0.17647059 0.18039216]
 [0.17647059 0.17647059 0.17254902 ... 0.17647059 0.17647059 0.17647059]
 [0.18039216 0.17254902 0.16862745 ... 0.17254902 0.17254902 0.17254902]
 ...
 [0.15294118 0.15294118 0.15294118 ... 0.15294118 0.15294118 0.16470588]
 [0.15686275 0.15294118 0.15294118 ... 0.15294118 0.15294118 0.16470588]
 [0.15686275 0.15686275 0.15294118 ... 0.15294118 0.15686275 0.16470588]] (3, 1)


error: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
from PIL import Image
im = Image.fromarray(np.uint8(dist2*255))
im.save('petko_test_mod.png')

In [ ]:
!zip -r colab.zip DenseDepth/

  adding: DenseDepth/ (stored 0%)
  adding: DenseDepth/utils.py (deflated 67%)
  adding: DenseDepth/__pycache__/ (stored 0%)
  adding: DenseDepth/__pycache__/layers.cpython-36.pyc (deflated 46%)
  adding: DenseDepth/__pycache__/utils.cpython-36.pyc (deflated 46%)
  adding: DenseDepth/model.py (deflated 68%)
  adding: DenseDepth/LICENSE (deflated 66%)
  adding: DenseDepth/demo_depth.npy (deflated 47%)
  adding: DenseDepth/nyu.h5 (deflated 8%)
  adding: DenseDepth/test.py (deflated 49%)
  adding: DenseDepth/.git/ (stored 0%)
  adding: DenseDepth/.git/packed-refs (deflated 10%)
  adding: DenseDepth/.git/refs/ (stored 0%)
  adding: DenseDepth/.git/refs/heads/ (stored 0%)
  adding: DenseDepth/.git/refs/heads/master (stored 0%)
  adding: DenseDepth/.git/refs/tags/ (stored 0%)
  adding: DenseDepth/.git/refs/remotes/ (stored 0%)
  adding: DenseDepth/.git/refs/remotes/origin/ (stored 0%)
  adding: DenseDepth/.git/refs/remotes/origin/HEAD (stored 0%)
  adding: DenseDepth/.git/objects/ (stored 0%

In [ ]:
!ls -l ./

total 224504
-rw-r--r-- 1 root root 183656061 Jul  3 16:05 bears.zip
drwxr-xr-x 8 root root      4096 Jul  3 15:09 DenseDepth
-rw-r--r-- 1 root root     22909 Jul  3 15:09 petko_test_mod.png
drwxr-xr-x 1 root root      4096 Jun 26 16:26 sample_data
-rw-r--r-- 1 root root  46199291 Jul  3 14:33 v1.15.3.tar.gz


In [ ]:
!unzip bears.zip

Archive:  bears.zip
   creating: DenseDepth/
  inflating: DenseDepth/test.py      
 extracting: DenseDepth/petko_test.png  
  inflating: DenseDepth/nyu.h5       
  inflating: DenseDepth/callbacks.py  
   creating: DenseDepth/.ipynb_checkpoints/
  inflating: DenseDepth/README.md    
  inflating: DenseDepth/DenseDepth.ipynb  
   creating: DenseDepth/Tensorflow/
  inflating: DenseDepth/Tensorflow/Evaluate.ipynb  
  inflating: DenseDepth/Tensorflow/DenseDepth.ipynb  
  inflating: DenseDepth/Tensorflow/model.py  
  inflating: DenseDepth/Tensorflow/loss.py  
  inflating: DenseDepth/Tensorflow/evaluate.py  
  inflating: DenseDepth/Tensorflow/data.py  
  inflating: DenseDepth/model.py     
  inflating: DenseDepth/loss.py      
  inflating: DenseDepth/LICENSE      
  inflating: DenseDepth/demo_rgb.npy  
  inflating: DenseDepth/evaluate.py  
  inflating: DenseDepth/utils.py     
  inflating: DenseDepth/train.py     
  inflating: DenseDepth/layers.py    
  inflating: DenseDepth/.gitignore   
   c